Modified the order in which the functions were declared in vdqm_SendRecv.c in order to avoid the following warnings:
[root@lxcastordev04 vdqm]# make | grep arning
vdqmc_SendRecv.c: In function `vdqm_AggregatorVolReq_Send':
vdqmc_SendRecv.c:1152: warning: implicit declaration of function `vdqm_AggregatorVolReq_Transfer'
vdqmc_SendRecv.c: At top level:
vdqmc_SendRecv.c:1161: warning: static declaration of 'vdqm_AggregatorVolReq_Transfer' follows non-static declaration
vdqmc_SendRecv.c:1152: warning: previous implicit declaration of 'vdqm_AggregatorVolReq_Transfer' was here
[root@lxcastordev04 vdqm]#