Due to the use of the K and R syntax the lun2fn function was being declared to be different in two different places.  I have now replaced the K and R declaration with a compatible Ansi C version.
rfio/lun2fn.c:33: error: ‘char* lun2fn’ redeclared as different kind of symbol
rfio_api.h:239: error: previous declaration of ‘char* lun2fn(int)’