Removed deprecated (in C++11) dynamic exception specifications from the mediachanger code.
Example error:

/home/smurray/CTA/mediachanger/io.hpp:353:3: error: dynamic exception
specifications are deprecated in C++11 [-Werror=deprecated]
   throw(cta::exception::TimeOut, cta::exception::Exception);
   ^~~~~